#!/bin/bash

echo "📋 Informations VPS Hostinger (ID: 942059)"
echo "=========================================="
echo ""
echo "🔍 Pour obtenir l'IP de votre VPS:"
echo "1. Allez sur: https://hpanel.hostinger.com/vps/942059/overview"
echo "2. Notez l'adresse IP publique"
echo "3. Notez les informations SSH"
echo ""
echo "📋 Informations typiques VPS Hostinger:"
echo "- IP publique: [À noter depuis l'interface]"
echo "- Port SSH: 22 (par défaut) ou autre"
echo "- Utilisateur: root (par défaut)"
echo "- OS: Ubuntu/CentOS (vérifier)"
echo ""
echo "🔐 Accès SSH type:"
echo "ssh root@[VOTRE_IP_VPS]"
echo ""
echo "⚠️  À faire ensuite:"
echo "1. Noter l'IP VPS depuis l'interface"
echo "2. Tester la connexion SSH"
echo "3. Configurer l'environnement (Node.js, PM2, Nginx)"
echo "4. Modifier les DNS pour pointer vers le VPS"